version: "3.8"

services:
  postgres:
    image: postgres:15   # Укажите нужную версию PostgreSQL
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"  # Проброс порта PostgreSQL
    environment:
      POSTGRES_USER: postgres  # Укажите имя пользователя
      POSTGRES_PASSWORD: postgres  # Укажите пароль
      POSTGRES_DB: postgres  # Укажите имя базы данных